### ISSUE TITLE
[calamares]: partition color codes not consistent when picking a replace partition

### ISSUE THREAD

**Issue by star-buck** [blue-systems/maui-netrunner-issues#22]
compare (first one ok, second wrong, third okay again):
![screenshot_20160727_092938](https://cloud.githubusercontent.com/assets/840070/17170935/ae0c8ae0-53ee-11e6-8dc1-0c2f4de648f9.png)
![screenshot_20160727_092959](https://cloud.githubusercontent.com/assets/840070/17170936/ae0e609a-53ee-11e6-9a72-a80e7a6d4cb4.png)
![screenshot_20160727_093011](https://cloud.githubusercontent.com/assets/840070/17170937/ae177c98-53ee-11e6-96f1-1de26cd07250.png)

http://pastebin.com/sAM721KC

**Comment by teo** [comment]
This is now fixed in master and the fix will be included in the next pre-release tarball.

As it turns out, this was definitely not a simple color numbering issue (and therefore not a simple fix), but a technical limitation of how logical partitions in an MSDOS partition table work: gaps in logical partition numbering are not allowed, and when a partition is deleted to perform a replace (or for any other reason), the numbers of other logical partitions may end up scrambled. In other words, /dev/sda1-style numbering is not just volatile on reboot, it is also volatile at runtime in certain situations.

As your screenshot shows, the consequence was not only scrambled colors, but also scrambled OS labels (e.g. Maui (18) disappears in the "after" line), because one or more partition paths change without updating the Osprober data structures and the colors cache. I've performed the necessary refactoring to have all Osprober usage and all color caching index partitions by filesystem UUID instead of by path.
