### ISSUE TITLE
[xembed-sni-proxy]: skype is taking 15 seconds for first start, then showing generic symbol in systray instead of skype state logo

### ISSUE THREAD

**Issue by star-buck** [blue-systems/maui-netrunner-issues#31]
tested in maui-18: http://dev.netrunner-os.com/dev/maui-18-dvd-64bit-build13-160728-1740.iso

**Comment by star-buck** [comment]
also noted that skype takes superlong to finally appear started, that didnt happen before in kde4 or early plasma 5?

**Comment by llelectronics** [comment]
I also have this here on first start on KDE SC 4.14. . I am suspecting a Skype issue but will investigate to see if we can fix it somehow.

**Comment by davidedmundson** [comment]
FWIW, I tested this on netrunner-core, and everything seems fine.
It loaded instantly and updated with the status fine. Even animated perfectly.

Downloading Maui now.

**Comment by star-buck** [comment]
interesting... so you extra installed it on of netrunner core ISO, which is debian, while maui 18 is neon.

**Comment by star-buck** [comment]
here is how it looks when skype started (i also noted that upon first start, skype takes 15 seconds and looks like it hangs before showing up):
![screenshot_20160730_134946](https://cloud.githubusercontent.com/assets/840070/17270164/a63d4b86-565c-11e6-9290-2ee82e6b925f.png)

**Comment by llelectronics** [comment]
I can confirm that

**Comment by davidedmundson** [comment]
Checked out the ISO...it isn't using xembed-sni-proxy

xembed-sni-proxy is the fallback for apps that only can use the legacy X method. This is talking to SNIs directly. I think Ubuntu has Qt4 patched to do that as Unity also uses the same spec as us.

Obviously we still have a bug, but:
 - it definitely isn't xembed-sni-proxy at fault (obviously, because that's my code :P ) 
 - it explains why we get different behaviour on the Debian system

DBus logs show the data from skype looks valid, and it's unlikely that's changed - and PlasmaShell is definitely getting told about the SNI and requesting the remaining data.

Bug will lie in either the system tray or KDE icon loading, both of which had quite a lot of changes recently.

**Comment by davidedmundson** [comment]
Icon fixed. Took me all day.

It's a bug in plasma-framework IconItem, as a fallback from whoever changed Icons to try and be smart and use plasma colours.

We start off with a valid pixmap icon
Plasma tries to see if it can theme it to Plasma colours
it can't - so it loads the original icon by name again (which is bloody stupid). 
Except now time it doesn't know to look in the right directory so it fails.

Patch on RB.

As for the startup delay....it seems that's a separate bug!
I know where that is at least; for some reason the SNI category is null, so it doesn't get shown. 
As to why....I'll investigate tomorrow.

**Comment by star-buck** [comment]
@davidedmundson : awesome stuff about the icon... now what does patch on RB mean again?

**Comment by davidedmundson** [comment]
RB == reviewboard. So waiting for someone to review it before merging. 
https://git.reviewboard.kde.org/r/128580/

**Comment by davidedmundson** [comment]
Icon fixes are all in Frameworks 5.25 which should be out in the next few days.

------

The startup delay is a problem with Qt4 and fonts.

debuggers/traces show it's spending it's time building up a cache of every font in the system.
It's probably slower now than it was before because Noto is magnitudes times larger than any other font.

You can make it slow again by deleting ~/.cache/fontconfig
running "QT_X11_NO_FONT_CONFIG=1 skype" is always super fast (but looks terrible)

So that's definitely the place:

So why only skype?

Because of the architecture.

All fonts have a cache in /var/cache/fontconfig which is normally generated when you install a font through a package manager.
libfontconfig is choosing not to use it, and making our own cache locally. No other app is doing this.

There's a line in the documentation for fc-cache; "Note that fc-cache must be executed once per architecture to generate font information customized for that architecture. "

I can reproduce the delay if I run another qt app under i386 (apt-get install qgit:i386)
 with the empty local font cache.

-----

What's the solution:
We need a separate font cache per architecture; probably by patching i386 libfontconfig; and by building i386 font caches when we install fonts.

I'm surprised Ubuntu doesn't do this, Arch seems to. Maybe it's to save disk space? 

---
There's also a third(!) skype related bug in Plasma if the application changes status before it's finished doing the initial loading, we can end up without an indicator. Super rare to hit, but I found it when starting skype a billion times. I'll get that fixed ASAP.

**Comment by star-buck** [comment]
@davidedmundson : can we set skype to use a different font, like dejavu?

**Comment by davidedmundson** [comment]
It won't help, this is called when we create the application before we've the app even sets or uses any fonts - and it's building a cache for every font on the system.

You could uinstall all the fonts, but I don't think that's a particularly good workaround.

Our only option is to build and ship a co-installable 32 bit version of fc-cache, which has the same font install hook as the 64 bit version to create a cache whenever a font is installed.

I filed a bug with Debian (as that's the root cause) https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=833531 and I think I might be able to make a packaging patch we can use.

**Comment by davidedmundson** [comment]
I've made a modified debian packaging for fontconfig, to also create a co-installable package of just fc-cache wtih the right install triggers. 

It would need to end up in one of the repositories used by Maui.
